### ISSUE TITLE
Issue: IntelliSense Functionality Lost After Installing

### ISSUE THREAD

**Issue by bashyftw** [lin2j/easy-deploy#11]
# Environment
IDE: CLion 2023.3.4
Operating System: Windows 10 with WSL 2
Plugin: Easy Deploy
Plugin Version: 1.3.6

# Description
After installing a Easy Deploy in CLion, all IntelliSense functionality was lost. The project still builds and runs correctly, but code completion, error highlighting, and other IntelliSense features stopped working. Disabling plugin fixs the problem.

**Comment by lin2j** [comment]
I downloaded CLion for testing and found that this issue does exist. The reason is that I added two C file type declarations in the **plugin.xml** file, which conflicts with the file type of CLion itself, causing the project file to fail to create an index. This can lead to the failure of functions such as code completion.

```xml
        <fileType implementationClass="tech.lin2j.idea.plugin.file.fileTypes.CFileType" fieldName="INSTANCE" name="C" extensions="c"/>
        <fileType implementationClass="tech.lin2j.idea.plugin.file.fileTypes.CppFileType" fieldName="INSTANCE" name="C++" extensions="cpp"/>
```

Sorry, I didn't consider these two as key file types for CLion before. I have made modifications and tested them, and they look normal now. If you are willing, you can download this temporary release or wait for the next release.

[Easy-Deploy-1.3.6.1.zip](https://github.com/user-attachments/files/16540213/Easy-Deploy-1.3.6.1.zip)

Modified screenshot
![image](https://github.com/user-attachments/assets/f39da171-6f29-4820-90bf-a78b0d21e873)
